version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - order-service
      - inventory-service

  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "6000:6000"
    depends_on:
      - mongo

  inventory-service:
    build: ./inventory-service
    ports:
      - "7000:7000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
